manager/urls.py
from django.urls import path

from manager.views import (
    index,
    TaskTypeListView,
    WorkerListView,
    TaskDetailView,
    TaskListView,
    WorkerDetailView,
    PositionListView,
    TaskTypeCreateView,
    PositionCreateView,
    TaskCreateView,
    WorkerCreateView,
    PositionUpdateView,
    TaskUpdateView,
    TaskTypeUpdateView,
    TaskDeleteView,
    PositionDeleteView,
    TaskTypeDeleteView,
    TaskWorkerUpdate,
    WorkerDeleteView,
    WorkerUpdateView,
)

app_name = "manager"

urlpatterns = [
    path("", index, name="index"),
    path(
        "task-types/",
        TaskTypeListView.as_view(),
        name="task-type-list"
    ),
    path(
        "task-types/create/",
        TaskTypeCreateView.as_view(),
        name="task-type-create"
    ),
    path(
        "task-types/<int:pk>/update/",
        TaskTypeUpdateView.as_view(),
        name="task-type-update"
    ),
    path(
        "task-types/<int:pk>/delete/",
        TaskTypeDeleteView.as_view(),
        name="task-type-delete"
    ),
    path("positions/", PositionListView.as_view(), name="position-list"),
    path("positions/create/", PositionCreateView.as_view(), name="position-create"),
    path("positions/<int:pk>/update/", PositionUpdateView.as_view(), name="position-update"),
    path("positions/<int:pk>/delete/", PositionDeleteView.as_view(), name="position-delete"),
    path("tasks/", TaskListView.as_view(), name="task-list"),
    path("tasks/<int:pk>/", TaskDetailView.as_view(), name="task-detail"),
    path("tasks/create/", TaskCreateView.as_view(), name="task-create"),
    path("tasks/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("tasks/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path("workers/", WorkerListView.as_view(), name="worker-list"),
    path(
        "workers/<int:pk>/",
        WorkerDetailView.as_view(),
        name="worker-detail"
    ),
    path("workers/create/", WorkerCreateView.as_view(), name="worker-create"),
    path("workers/<int:pk>/update/", WorkerUpdateView.as_view(), name="worker-update"),

    path("workers/<int:pk>/delete/", WorkerDeleteView.as_view(), name="worker-delete"),
    path(
        "task/<int:pk>/task_worker_update/",
        TaskWorkerUpdate.as_view(),
        name="task-worker-update"
    ),
]

task_manager/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("manager.urls", namespace="manager")),
    path("__debug__/", include("debug_toolbar.urls"))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

manager/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _


class TaskType(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Position(models.Model):
    name = models.CharField(max_length=255, null=False)

    def __str__(self):
        return self.name


class Worker(AbstractUser):
    position = models.ForeignKey(Position, on_delete=models.CASCADE, null=True, blank=True)

    class Meta:
        verbose_name = "worker"
        verbose_name_plural = "workers"

    def __str__(self):
        return f"{self.username} ({self.first_name} {self.last_name})"


class Task(models.Model):
    class Priority(models.TextChoices):
        LOW = "LO", _("Low")
        NORMAL = "NO", _("Normal")
        HIGH = "HI", _("High")
        URGENT = "UR", _("Urgent")

    name = models.CharField(max_length=255)
    description = models.TextField(max_length=255)
    deadline = models.DateField(null=True)
    is_completed = models.BooleanField(default=False)
    priority = models.CharField(max_length=2, choices=Priority.choices, default=Priority.NORMAL)
    task_type = models.ForeignKey(TaskType, on_delete=models.CASCADE)
    assignees = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="tasks")

    def __str__(self):
        return f"{self.name} with {self.priority} priority"

manager/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from manager.models import Worker, Task


class WorkerCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Worker
        fields = UserCreationForm.Meta.fields + ("first_name", "last_name", "position",)


class DateInput(forms.DateInput):
    input_type = "date"


class TaskForm(forms.ModelForm):
    assignees = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

    deadline = forms.DateField(
        widget=DateInput()
    )

    class Meta:
        model = Task
        fields = "__all__"


class SearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Search by name"
            }
        )
    )


class TaskSearchForm(SearchForm):
    pass


class TaskTypeSearchForm(SearchForm):
    pass


class PositionSearchForm(SearchForm):
    pass


class WorkerSearchForm(forms.Form):
    username = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Search by username"
            }
        )
    )

manager/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views import generic, View
from manager.forms import (
    WorkerCreationForm,
    TaskForm,
    TaskSearchForm,
    PositionSearchForm,
    TaskTypeSearchForm,
    WorkerSearchForm
)
from manager.models import Worker, Task, Position, TaskType


@login_required
def index(request):
    num_workers = Worker.objects.count()
    num_tasks = Task.objects.count()
    num_positions = Position.objects.count()
    num_task_type = TaskType.objects.count()

    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "num_workers": num_workers,
        "num_tasks": num_tasks,
        "num_positions": num_positions,
        "num_task_type": num_task_type,
        "num_visits": num_visits,
    }

    return render(request, "manager/index.html", context=context)


class TaskTypeListView(LoginRequiredMixin, generic.ListView):
    model = TaskType
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TaskTypeListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = TaskTypeSearchForm(
            initial={"name": name}
        )
        return context

    def get_queryset(self):
        queryset = TaskType.objects.order_by("name")
        form = TaskTypeSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(name__icontains=form.cleaned_data["name"])
        return queryset


class TaskTypeCreateView(LoginRequiredMixin, generic.CreateView):
    model = TaskType
    fields = "__all__"
    success_url = reverse_lazy("manager:task-type-list")
    template_name = "manager/tasktype_form.html"


class TaskTypeUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = TaskType
    fields = "__all__"
    success_url = reverse_lazy("manager:task-type-list")
    template_name = "manager/tasktype_form.html"


class TaskTypeDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = TaskType
    template_name = "manager/tasktype_confirm_delete.html"
    success_url = reverse_lazy("manager:task-type-list")


class PositionListView(LoginRequiredMixin, generic.ListView):
    model = Position
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PositionListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = PositionSearchForm(
            initial={"name": name}
        )
        return context

    def get_queryset(self):
        queryset = Position.objects.order_by("name")
        form = PositionSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(name__icontains=form.cleaned_data["name"])
        return queryset


class PositionCreateView(LoginRequiredMixin, generic.CreateView):
    model = Position
    fields = "__all__"
    success_url = reverse_lazy("manager:position-list")
    template_name = "manager/position_form.html"


class PositionUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Position
    fields = "__all__"
    success_url = reverse_lazy("manager:position-list")
    template_name = "manager/position_form.html"


class PositionDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Position
    template_name = "manager/position_confirm_delete.html"
    success_url = reverse_lazy("manager:position-list")


class TaskListView(LoginRequiredMixin, generic.ListView):
    model = Task
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TaskListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = TaskSearchForm(
            initial={"name": name}
        )
        return context

    def get_queryset(self):
        queryset = Task.objects.all()
        form = TaskSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(name__icontains=form.cleaned_data["name"])
        return queryset


class TaskDetailView(LoginRequiredMixin, generic.DetailView):
    model = Task


class TaskCreateView(LoginRequiredMixin, generic.CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("manager:task-list")


class TaskUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("manager:task-list")


class TaskDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Task
    template_name = "manager/task_confirm_delete.html"
    success_url = reverse_lazy("manager:task-list")


class WorkerListView(LoginRequiredMixin, generic.ListView):
    model = Worker
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(WorkerListView, self).get_context_data(**kwargs)
        username = self.request.GET.get("username", "")
        context["search_form"] = WorkerSearchForm(
            initial={"username": username}
        )
        return context

    def get_queryset(self):
        queryset = Worker.objects.all()
        form = WorkerSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(username__icontains=form.cleaned_data["username"])
        return queryset


class WorkerDetailView(LoginRequiredMixin, generic.DetailView):
    model = Worker
    queryset = Worker.objects.prefetch_related("tasks__assignees")


class WorkerCreateView(LoginRequiredMixin, generic.CreateView):
    model = Worker
    form_class = WorkerCreationForm
    success_url = reverse_lazy("manager:worker-list")


class WorkerUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Worker
    form_class = WorkerCreationForm
    success_url = reverse_lazy("manager:worker-list")


class WorkerDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Worker
    template_name = "manager/worker_confirm_delete.html"
    success_url = reverse_lazy("manager:worker-list")


@method_decorator(login_required, name="dispatch")
class TaskWorkerUpdate(View):

    def get(self, request, pk):
        worker = request.user
        task = Task.objects.get(pk=pk)
        if worker in task.assignees.all():
            task.assignees.remove(worker)
        else:
            task.assignees.add(worker)
        return redirect("manager:task-detail", pk=pk)

templates/manager/index.html
{% extends "layouts/base_sections.html" %}
{% load static %}

{% block title %}{% endblock title %}

{% block body %} class="index-page bg-gray-200" {% endblock body %}

{% block content %}

  <header class="header-2">
    <div class="page-header min-vh-75 relative"
         style="background-image: url('{% static 'img/curved.jpg' %}')">
      <div class="container">
        <div class="row">
          <div class="col-lg-7 text-center mx-auto">
            <h1 class="text-white pt-3 mt-n5">
              <a class="text-white" target="_blank">Task Manager Service Home</a>
            </h1>
            <p class="lead text-white mt-3">Welcome to Best Task Manager!</p>
          </div>
        </div>
      </div>

      <div class="position-absolute w-100 z-index-1 bottom-0">
        <svg class="waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
             viewBox="0 24 150 40" preserveAspectRatio="none" shape-rendering="auto">
          <defs>
            <path id="gentle-wave" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z"/>
          </defs>
          <g class="moving-waves">
            <use xlink:href="#gentle-wave" x="48" y="-1" fill="rgba(255,255,255,0.40"/>
            <use xlink:href="#gentle-wave" x="48" y="3" fill="rgba(255,255,255,0.35)"/>
            <use xlink:href="#gentle-wave" x="48" y="5" fill="rgba(255,255,255,0.25)"/>
            <use xlink:href="#gentle-wave" x="48" y="8" fill="rgba(255,255,255,0.20)"/>
            <use xlink:href="#gentle-wave" x="48" y="13" fill="rgba(255,255,255,0.15)"/>
            <use xlink:href="#gentle-wave" x="48" y="16" fill="rgba(255,255,255,0.95"/>
          </g>
        </svg>
      </div>
    </div>
  </header>


  <section class="pt-3 pb-4" id="count-stats">
    <div class="container">
      <div class="row">
        <div class="col-lg-9 z-index-2 border-radius-xl mt-n10 mx-auto py-3 blur shadow-blur">
          <div class="row">
            <div class="col-md-4 position-relative">
              <div class="p-3 text-center">
                <h1 class="text-gradient text-primary"><span id="state1" countTo={{ num_task_type }}></span> +</h1>
                <h5 class="mt-3">Task Types</h5>
                <p class="text-sm">Task types offer an efficient categorization system, allowing seamless organization and prioritization within the Task Manager app.</p>
              </div>
              <hr class="vertical dark">
            </div>
            <div class="col-md-4 position-relative">
              <div class="p-3 text-center">
                <h1 class="text-gradient text-primary"><span id="state2" countTo={{ num_workers }}></span> +</h1>
                <h5 class="mt-3">Workers</h5>
                <p class="text-sm">Workers form the backbone of productivity, contributing their skills and dedication to accomplish tasks efficiently within any organization.</p>
              </div>
              <hr class="vertical dark">
            </div>
            <div class="col-md-4">
              <div class="p-3 text-center">
                <h1 class="text-gradient text-primary"><span id="state3" countTo={{ num_tasks }}></span> +</h1>
                <h5 class="mt-3">Tasks</h5>
                <p class="text-sm">Tasks serve as actionable milestones, guiding the path toward achieving goals and objectives within any project or workflow.</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>



{% endblock content %}

{% block javascripts %}

  <script type="text/javascript">

      if (document.getElementById('state1')) {
          const countUp = new CountUp('state1', document.getElementById("state1").getAttribute("countTo"));
          if (!countUp.error) {
              countUp.start();
          } else {
              console.error(countUp.error);
          }
      }
      if (document.getElementById('state2')) {
          const countUp1 = new CountUp('state2', document.getElementById("state2").getAttribute("countTo"));
          if (!countUp1.error) {
              countUp1.start();
          } else {
              console.error(countUp1.error);
          }
      }
      if (document.getElementById('state3')) {
          const countUp2 = new CountUp('state3', document.getElementById("state3").getAttribute("countTo"));
          if (!countUp2.error) {
              countUp2.start();
          } else {
              console.error(countUp2.error);
          }
          ;
      }
  </script>

{% endblock javascripts %}

templates/manager/position_confirm_delete.html
{% extends "layouts/base_sections.html" %}
{% block content %}
{% include "includes/page_header.html" with page_title="Delete Position" %}
  <section class="pt-3 pb-4" id="count-stats">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-5 z-index-5 border-radius-xl mt-n12 mx-auto py-3 blur shadow-blur">
          <form action="" method="post">
            {% csrf_token %}
            <div class="text-center">
              <p>Are you sure you want to delete the position: {{ position.name }}?</p>
              <input type="submit" value="Yes, delete" class="btn btn-danger">
              <a href="{% url 'manager:position-list'%}" class="btn btn-primary">
                Cancel
              </a>
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

templates/manager/position_form.html
{% extends "layouts/base_sections.html" %}
{% load crispy_forms_filters %}
{% block content %}
{% include "includes/page_header.html" with page_title="Editing a position" %}
  <section class="pt-3 pb-4" id="count-stats">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-5 z-index-5 border-radius-xl mt-n12 mx-auto py-3 blur shadow-blur">
          <h1 class="row justify-content-center">{{ object|yesno:"Update,Create" }}</h1>
          <form action="" method="post" novalidate>
            {% csrf_token %}
            {{ form|crispy }}
            <div class="text-center">
              <input class="btn btn-primary" type="submit" value="Submit">
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

templates/manager/position_list.html
{% extends "layouts/base_sections.html" %}
{% load static %}
{% load crispy_forms_filters %}
{% block content %}
  {% include 'includes/page_header.html' with page_title="Positions" %}
  <section>
    <div class="container">
      <div class="row">
        <div class="col-lg-6 z-index-7 border-radius-xl mt-n12 mx-auto py-3 blur shadow-blur">
          <div class="row">
            <form method="get" action="" class="form-inline">
              <div class="input-group justify-content-xl-center">
                {{ search_form|crispy }}
                <div class="input-group-append">
                  <button type="submit" class="btn btn-secondary" id="search-btn">
                    🔍
                  </button>
                </div>
                <a class="justify-content-xl-end btn btn-primary" href="{% url 'manager:position-create' %}">
                  +
                </a>
              </div>
            </form>
            {% if position_list %}
              <table class="table">
                <tr>
                  <th>Position</th>
                  <th>Update</th>
                  <th>Delete</th>
                </tr>
                {% for position in position_list %}
                  <tr>
                    <td>{{ position.name }}</td>
                    <td><a href="{% url 'manager:position-update' pk=position.id %}" class="btn btn-warning">UPDATE</a></td>
                    <td><a href="{% url 'manager:position-delete' pk=position.id %}" class="btn btn-danger">DELETE</a></td>
                  </tr>
                {% endfor %}
              </table>
            {% else %}
              <h1 class="row justify-content-center">There aren't any positions</h1>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

templates/manager/task_confirm_delete.html
{% extends "layouts/base_sections.html" %}
{% block content %}
  {% include "includes/page_header.html" with page_title="Delete Task" %}
  <section class="pt-3 pb-4" id="count-stats">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-5 z-index-5 border-radius-xl mt-n10 mx-auto py-3 blur shadow-blur">
          <form action="" method="post">
            {% csrf_token %}
            <div class="text-center">
              <p>Are you sure you want to delete the task: {{ task.name }}?</p>
              <p><i>All Task Type with this task will also be deleted</i></p>
              <input type="submit" value="Yes, delete" class="btn btn-danger">
              <a href="{% url 'manager:task-detail' pk=task.id %}" class="btn btn-primary">
                Cancel
              </a>
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

templates/manager/task_form.html
{% extends "layouts/base_sections.html" %}
{% load crispy_forms_filters %}
{% block content %}
{% include "includes/page_header.html" with page_title="Editing a task" %}
  <section class="pt-3 pb-4" id="count-stats">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-5 z-index-5 border-radius-xl mt-n12 mx-auto py-3 blur shadow-blur">
          <h1 class="row justify-content-center">{{ object|yesno:"Update,Create" }}</h1>
          <form action="" method="post" novalidate>
            {% csrf_token %}
            {{ form|crispy }}
            <div class="text-center">
              <input class="btn btn-primary" type="submit" value="Submit">
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

templates/manager/task_list.html
{% extends "layouts/base_sections.html" %}
{% load static %}
{% load crispy_forms_filters %}
{% block content %}
  {% include "includes/page_header.html" with page_title="Tasks" %}
  <section class="pt-3 pb-4" id="count-stats">
    <div class="container">
      <div class="row">
        <div class="col-lg-7 z-index-5 border-radius-xl mt-n12 mx-auto py-3 blur shadow-blur">
          <div class="row">
            <form method="get" action="" class="form-inline">
              <div class="input-group justify-content-xl-center">
                {{ search_form|crispy }}
                <div class="input-group-append">
                  <button type="submit" class="btn btn-secondary" id="search-btn">
                    🔍
                  </button>
                </div>
                <a class="justify-content-xl-end btn btn-primary" href="{% url 'manager:task-create' %}">
                  +
                </a>
              </div>
            </form>
            {% if task_list %}
              <table class="table">
                <tr>
                  <th>Task name</th>
                  <th>Deadline</th>
                  <th>Priority</th>
                </tr>
                {% for task in task_list %}
                  <tr>
                    <td>
                      <a href="{% url 'manager:task-detail' task.id %}">
                        {{ task.name }}
                      </a>
                    </td>
                    <td>{{ task.deadline }}</td>
                    <td>{{ task.priority }}</td>
                  </tr>
                {% endfor %}
              </table>
            {% else %}
              <h1 class="row justify-content-center">There aren't any types</h1>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

templates/manager/tasktype_confirm_delete.html
{% extends "layouts/base_sections.html" %}
{% block content %}
{% include "includes/page_header.html" with page_title="Delete Task Type" %}
  <section class="pt-3 pb-4" id="count-stats">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-5 z-index-5 border-radius-xl mt-n12 mx-auto py-3 blur shadow-blur">
          <form action="" method="post">
            {% csrf_token %}
            <div class="text-center">
              <p>Are you sure you want to delete the task type: {{ tasktype.name }}?</p>
              <input type="submit" value="Yes, delete" class="btn btn-danger">
              <a href="{% url 'manager:task-type-list'%}" class="btn btn-primary">
                Cancel
              </a>
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

templates/manager/tasktype_list.html
{% extends "layouts/base_sections.html" %}
{% load static %}
{% load crispy_forms_filters %}
{% block content %}
  {% include 'includes/page_header.html' with page_title="Task Types" %}
  <section>
    <div class="container">
      <div class="row">
        <div class="col-lg-6 z-index-7 border-radius-xl mt-n12 mx-auto py-3 blur shadow-blur">
          <form method="get" action="" class="form-inline">
            <div class="input-group justify-content-xl-center">
              {{ search_form|crispy }}
              <div class="input-group-append">
                <button type="submit" class="btn btn-secondary" id="search-btn">
                  🔍
                </button>
              </div>
              <a class="justify-content-xl-end btn btn-primary" href="{% url 'manager:task-type-create' %}">
                +
              </a>
            </div>
          </form>
          <div class="row">
            {% if tasktype_list %}
              <table class="table">
                <tr>
                  <th>Task Type</th>
                  <th>Update</th>
                  <th>Delete</th>
                </tr>
                {% for tasktype in tasktype_list %}
                  <tr>
                    <td>{{ tasktype.name }}</td>
                    <td><a href="{% url 'manager:task-type-update' pk=tasktype.id %}" class="btn btn-warning">Update</a>
                    </td>
                    <td><a href="{% url 'manager:task-type-delete' pk=tasktype.id %}" class="btn btn-danger">Delete</a>
                    </td>
                  </tr>
                {% endfor %}
              </table>
            {% else %}
              <h1 class="row justify-content-center">There aren't any types</h1>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

templates/manager/worker_confirm_delete.html
{% extends "layouts/base_sections.html" %}
{% block content %}
  {% include "includes/page_header.html" with page_title="Delete Worker" %}
  <section class="pt-3 pb-4" id="count-stats">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-5 z-index-5 border-radius-xl mt-n10 mx-auto py-3 blur shadow-blur">
          <form action="" method="post">
            {% csrf_token %}
            <div class="text-center">
              <p>Are you sure you want to delete the worker: {{ worker.username }}?</p>
              <input type="submit" value="Yes, delete" class="btn btn-danger">
              <a href="{% url 'manager:worker-detail' pk=worker.id %}" class="btn btn-primary">
                Cancel
              </a>
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

templates/manager/worker_detail.html
{% extends "layouts/base_sections.html" %}
{% load static %}
{% block content %}
  <div class="page-header min-vh-75 relative">
    <div class="col-lg-5 text-center mx-auto">
      <h1 class="pt-3 mt-n6">
        Worker in detail
        <a href="{% url 'manager:worker-delete' pk=worker.id %}" class="btn btn-danger link-to-page">
          Delete
        </a>
        <a href="{% url 'manager:worker-update' pk=worker.id %}" class="btn btn-secondary link-to-page">
          Update
        </a>
      </h1>
    </div>
  </div>
  <section class="pt-3 pb-4" id="count-stats">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-4 z-index-4 border-radius-xl mt-n12 mx-auto py-3 blur shadow-blur">
          <p>Username: {{ worker.username }}</p>
          <p>First name: {{ worker.first_name }}</p>
          <p>Last name: {{ worker.last_name }}</p>
          <p>Position: {{ worker.position }}</p>
          {% if worker.tasks.all %}
            <p><strong>{{ worker.username }} task{{ worker.tasks.count|pluralize }}:</strong></p>
            {% for task in worker.tasks.all %}
              <p>{{ task.id }} {{ task.name }} <a href="{% url 'manager:task-detail' pk=task.id %}">More</a></p>
            {% endfor %}
          {% endif %}
        </div>
      </div>
    </div>
  </section>
{% endblock %}

templates/manager/worker_list.html
{% extends "layouts/base_sections.html" %}
{% load static %}

{% load crispy_forms_filters %}
{% block content %}
  {% include 'includes/page_header.html' with page_title="Workers" %}
  <section class="pt-3 pb-4" id="count-stats">
    <div class="container">
      <div class="row">
        <div class="col-lg-9 z-index-5 border-radius-xl mt-n12 mx-auto py-3 blur shadow-blur">
          <div class="row mb-2 justify-content-center">
            <form method="get" action="" class="form-inline">
              <div class="input-group justify-content-xl-center">
                {{ search_form|crispy }}
                <div class="input-group-append">
                  <button type="submit" class="btn btn-secondary" id="search-btn">
                    🔍
                  </button>
                </div>
                <a class="justify-content-xl-end btn btn-primary" href="{% url 'manager:worker-create' %}">
                  +
                </a>
              </div>
            </form>
            <div class="row">
              {% if worker_list %}
                <table class="table">
                  <tr>
                    <th>ID</th>
                    <th>Username</th>
                    <th>First name</th>
                    <th>Last name</th>
                    <th>Position</th>
                  </tr>
                  {% for worker in worker_list %}
                    <tr>
                      <td>
                        <a href="{% url 'manager:worker-detail' worker.id %}">
                          {{ worker.id }}
                        </a>
                      </td>
                      <td>{{ worker.username }}</td>
                      <td>{{ worker.first_name }}</td>
                      <td>{{ worker.last_name }}</td>
                      <td>{{ worker.position }}</td>
                    </tr>
                  {% endfor %}
                </table>
              {% else %}
                <h1 class="row justify-content-center">There aren't any workers</h1>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}